### ISSUE TITLE
Code Maintenance Task List

### ISSUE THREAD

**Issue by Puddlestomper** [TheCherno/Hazel#140]
As suggested @LovelySanta, this issue is meant for us to make a full list of everything that needs to be done in the next code maintenance episode/PR/session.

**Please note that no PRs need to be made directly into the master branch for these issues, but rather that any PRs should be made to the [maintenance branch](https://github.com/LovelySanta/Hazel/tree/Code-Maintenance).**

## Pull Request 1: Updating code base (#165) [Merged]

- [x] Make sure all `Create` methods return a `Ref`/`Scope` as appropriate and fix all uses of these methods accordingly (originally in #112).
      *This was mentioned in the episode about Refs and Scopes.*
  - [x] `GraphicsContext`
  - [x] `VertexBuffer`
  - [x] `IndexBuffer`
  - [x] `VertexArray`
  - [x] `Shader`
  - [x] `Texture`
  - [x] `RendererAPI`
  - [x] ~~`Window`~~
  - [x] ~~`Input`~~
  - [x] ~~`Application`~~
- [x] Change other smart pointers where possible
  - [x] `Log` class
- [x] Remove all remaining dll traces like the `HZ_BUILD_DLL` and `HAZEL_API` defines.
      *This was mentioned when we converted Hazel to a static library.*
- [x] Fix include statements
  - [x] All includes should be relative to `Hazel/src` and not relative to where the file is located.
      *This was mentioned in the episode of the CameraController.*
  - [x] Include `Core.h` in `Hazel.h`
  - [x] External includes should use `<>` instead of `""`
- [x] Remove the `BIND_EVENT_FN` in Application and replace it with the `HZ_BIND_EVENT_FN` instead
- [x] Use default constructor instead of empty constructor
  - [x] `LayerStack`
  - [x] `ApplicationEvents`
- [x] Clean up code copied into `Renderer2D.cpp`
  - [x] Remove `Hazel::` namespace on line 72
  - [x] `squareVertices` array size is too big (`5 * 4` instead of `3 * 4`)
  - [x] Errors in Renderer2D due to create functions returning a ref
- [x] Remove obsolete glwf logging messages init + terminate
    *Requested by Cherno in Discord*
- [x] Remove obsolete YAML keys in PR template
- [x] Add `Shutdown` method in `Renderer` and call it. Also call the `Renderer2D` `Shutdown` method in it, since it is currently not being called and not freeing the data in `Renderer2DStorage`.
   *This was mentioned in ["Starting our 2D Renderer"](https://youtu.be/r_5fF1AxgpU?t=1490)*
- [x] Remove OpenGL calls in Renderer.
    *This was mentioned in the video about 2D renderer textures.* https://github.com/TheCherno/Hazel/blob/0f583671c23c7a5e799269b791bc3d6220f99d22/Hazel/src/Hazel/Renderer/Renderer.cpp#L31-L39

## Pull Request 2: Fixing all warnings
- IntelliSense warnings
  - [ ] [`Event.h`] The enum type 'Hazel::EventCategory' is unscoped. 
  - [ ] [`Buffer.h`] Variable 'Hazel::BufferElement::xxx' is uninitialized.
    - [ ] 'Hazel::BufferElement::Normalised'
    - [ ] 'Hazel::BufferElement::Offset'
    - [ ] 'Hazel::BufferElement::Type'
  - [ ] [`WindowsWindow.h`] Variable 'Hazel::WindowsWindow::WindowData::xxx' is uninitialized. 
    - [ ] 'Hazel::WindowsWindow::WindowData::Height'
    - [ ] 'Hazel::WindowsWindow::WindowData::VSync'
    - [ ] 'Hazel::WindowsWindow::WindowData::Width'
  - [ ] [spdlog submodule] Spitting out unwanted warnings
  - [ ] [ImGui submodule] Spitting out unwanted warnings
  - [ ] [GLFW submodule] Spitting out unwanted warnings
	

I've undoubtedly missed some so feel free to comment and the mods or I will add them as soon as I can.

**Comment by LovelySanta** [comment]
context should also have a create function: https://github.com/TheCherno/Hazel/blob/033af46fd59623f0a7ffa53344b4d3454ff28da8/Hazel/src/Platform/Windows/WindowsWindow.cpp#L53

**Comment by LovelySanta** [comment]
Unchecked the All includes should be relative to `Hazel/src` due to cherno's last commit

**Comment by LovelySanta** [comment]
Unchecked `Window` as I found some unique pointers in application to create a window
also input must get a decent input create function.

I am aware this is not by checking the api, but rather the platform. I'll look tomorrow into it.

**Comment by LovelySanta** [comment]
Since the other warnings are just IntelliSense warnings, I'll close this.
