### ISSUE TITLE
Memory leak in Hazel?

### ISSUE THREAD

**Issue by CleverSource** [TheCherno/Hazel#47]
This is what I had to say on the Discord:
![image](https://user-images.githubusercontent.com/21996470/53761891-aa9cde80-3e94-11e9-8af0-889042037e41.png)

I don't know what causes this and am still debugging it but I have managed to experience this memory leak 2 out of 10 runs in a row. This is a definite memory leak, just I can't find the root cause. I would love to discuss more of this with people and discover possible solutions, and I want to bring this to Cherno's attention. 

Thanks.👍 

# Task list
- [x] Delete created shaders after created program (TheCherno/Hazel#126)
- [x] Delete created shaders after created program (TheCherno/Hazel#127)
- [x] Call GLFWterminate (TheCherno/Hazel#128)
- [x] Use scopes instead of raw pointers (TheCherno/Hazel#129)
- [ ] Test if there are more leaks

EDIT by @LovelySanta: Added task list

**Comment by gabrielevierti** [comment]
What exactly are you experiencing? Have you tried running the program in debug mode? Did you find something interesting we might wanna take a look at? In all Honesty I haven't had any sort of problem so far :(

**Comment by badryasuo** [comment]
I'm having the same problem!! Memory leaks just by moving the demo window or moving it outside of the application + it drops a lot of FPS & lags when moving the demo window as you can see.. 16 FPS; That's definitely a bug either in Hazel or ImGui docking branch. p.s I'm using the latest commit.
![image](https://user-images.githubusercontent.com/30192597/57565001-b8e80900-73b5-11e9-90c9-0d6b1c9df28b.png)

**Comment by badryasuo** [comment]
Sandbox.exe has used over 7GB of my RAM when I've left the demo window outside of the viewport for some minutes. I confirm it's a **bug**.

**Comment by live627** [comment]
This might be fixed in #49

**Comment by Gaztin** [comment]
Can anyone who had this problem before confirm if it has been fixed or not? @CleverSource or @badryasuo or anyone else.

**Comment by gold604** [comment]
@Gaztin I can confirm there's no memory leak on my machine. However there was a missing semicolon introduced in #49. I've already created new PR #72 which is waiting to be merged.

**Comment by gold604** [comment]
I'd like to note that #49 introduced a missing semicolon. I've already created new PR #72 which fixes that and is ready to be merged. 

For now, you can manually add a semicolon in LayerStack.cpp at the end of the line 34.

**Comment by CleverSource** [comment]
@Gaztin I still experience a few memory issues but I updated ImGui docking branch and it seems to have gotten better, it still has a massive memory spike but it's much more subtle than before. It possibly was coming from docking, maybe have Cherno merge the current ImGui docking branch with his personal ImGui fork?

**Comment by Gaztin** [comment]
The ImGui fork has not been updated since February. Hopefully we can update it soon to see if it solves the current memory problems.

**Comment by LovelySanta** [comment]
Also, there is still a known leak when we close the application as we don't call `glfwTerminate` anywhere.
https://github.com/TheCherno/Hazel/blob/982dcdfc5afe2ce74cb8297ad4e3c8fad79fc831/Hazel/src/Platform/Windows/WindowsWindow.cpp#L42-L49

**Comment by WhoseTheNerd** [comment]
> Also, there is still a known leak when we close the application as we don't call `glfwTerminate` anywhere.
> 
> https://github.com/TheCherno/Hazel/blob/982dcdfc5afe2ce74cb8297ad4e3c8fad79fc831/Hazel/src/Platform/Windows/WindowsWindow.cpp#L42-L49

The problem is that the @TheCherno wants support for multiple windows, but GLFW initialization should happen at once, so I think that the GLFW initialization should be moved into its own class.
Why we should do this is because any GLFW returned objects are allocated internally and can be freed when we call `glfwTerminate();` Here's a link to the [documentation](https://www.glfw.org/docs/latest/group__init.html#gaaae48c0a18607ea4a4ba951d939f0901)

**Comment by LovelySanta** [comment]
> The problem is that the @TheCherno wants support for multiple windows, but GLFW initialization should happen at once, so I think that the GLFW initialization should be moved into its own class.
> Why we should do this is because any GLFW returned objects are allocated internally and can be freed when we call `glfwTerminate();` Here's a link to the [documentation](https://www.glfw.org/docs/latest/group__init.html#gaaae48c0a18607ea4a4ba951d939f0901)

An easy solution to keep GLFW inside WindowsWindow, keep a `static uint_8 s_WindowCount` to track the amount (max 255) of windows that are open.
- In the constructor
  - If `s_WindowCount` equals 0, no windows are already open, so we need to initialize GLFW
  - Increment the counter
- In the deconstructor
  - Decrement the counter
  - If `s_WindowCount` equals 0, we just closed the last window, so we need to terminate GLFW

This results in the same amount of memory used (that byte for counter or for bool, and no extra classes, this stays contained in WindowsWindow)

Thoughts?

**Comment by WhoseTheNerd** [comment]
My solution would be simple and elegant. Managing like a ref counting can get very complicated.
In EntryPoint.h
```c
...
int main(int argc, char** argv)
{
    Hazel::System system;
    Hazel::Log::Init();
    auto app = Hazel::CreateApplication();
    app->Run():
}
...
```

**Comment by LovelySanta** [comment]
> In EntryPoint.h
> 
> ```c
> ...
> int main(int argc, char** argv)
> {
>     Hazel::System system;
>     Hazel::Log::Init();
>     auto app = Hazel::CreateApplication();
>     app->Run():
> }
> ...
> ```

That was my idea before you [commented on the linux PR](https://github.com/TheCherno/Hazel/pull/82#issuecomment-515558428); where I assumed you would want a single entrypoint...

On the other had, depending on the distributions, we might want/not want to have GLFW used; where containing it inside the WindowsWindow (where we are actualy using it), could help to keep GLFW contained to where it is used in the code base...

Having a System around could make our lives alot easier when defining stuff like what renderer we use.. There we could setup all the precompiler stuff that will contain distribution specific stuff, for example defining what renderer we use:
https://github.com/TheCherno/Hazel/blob/5dc2ee187fae6a3efa1d13b61faf5ca67e3638bd/Hazel/src/Hazel/Renderer/RendererAPI.cpp#L6
However, instead of creating an instance at that point, keeping it all static might be handy so we can access it everywhere in the code base...

**Comment by bovacu** [comment]
Hi, I wrote another memory leak issue I found on issue #96 and I've been told to share here the problem so everything is together. You can read the issue for full info and the full log of memory leaks, but i'm doing a little sum up.

Important: I've checked this issue on both my repo and last repo of Hazel, so is not just a problem of mine.

I was wandering if there was any memory leaks during the writing of the code (just in case I missed something or wrote something wrong) so I looked for a library to check memory leaks on Windows and the web page of Visual Studio gave this code (marked with <-):

```
#ifdef CGE_WINDOWS
extern CGE::Game* CGE::BuildGame();

#define _CRTDBG_MAP_ALLOC      <-
#include <stdlib.h>                        <-
#include <crtdbg.h>                      <-

int main(int argc, char** argv) {
	CGE::Logger::initLogger();

	auto _game = CGE::BuildGame();
	_game->run();
	delete _game;

	_CrtDumpMemoryLeaks();      <-
}
 #else
#error Only windows supported yet
#endif
```

As I wrote on top, the full log is in the issue #96 (I can post it here if needed) and there's a lot of memory leaks. I figured out that they appear once on the premake we start using
`buildoptions "/MDd" / buildoptions "/MD"`

what we change to

`runtime "Debug" / runtime "Release"`
and
`staticruntime "Off"`

The only pointers we have to delete are the Layers from the LayerStack and we are deleting them, so it might be some GLFW problem where we aren't calling a specific function that needs to be called (?)

I don't really know, so any suggestion is welcomed. As I said, the output of the code provided by Visual Studio is here #96 and there are a lot of memory leaks.

**Comment by LovelySanta** [comment]
As @bovacu discussed in #96, it does still happen on the most recent builds of Hazel.
All relevant information is posted here, closing #96 as duplicate.

**Comment by WhoseTheNerd** [comment]
> > In EntryPoint.h
> > ```c
> > ...
> > int main(int argc, char** argv)
> > {
> >     Hazel::System system;
> >     Hazel::Log::Init();
> >     auto app = Hazel::CreateApplication();
> >     app->Run():
> > }
> > ...
> > ```
> 
> That was my idea before you [commented on the linux PR](https://github.com/TheCherno/Hazel/pull/82#issuecomment-515558428); where I assumed you would want a single entrypoint...
> 
> On the other had, depending on the distributions, we might want/not want to have GLFW used; where containing it inside the WindowsWindow (where we are actualy using it), could help to keep GLFW contained to where it is used in the code base...
> 
> Having a System around could make our lives alot easier when defining stuff like what renderer we use.. There we could setup all the precompiler stuff that will contain distribution specific stuff, for example defining what renderer we use:
> https://github.com/TheCherno/Hazel/blob/5dc2ee187fae6a3efa1d13b61faf5ca67e3638bd/Hazel/src/Hazel/Renderer/RendererAPI.cpp#L6
> 
> 
> However, instead of creating an instance at that point, keeping it all static might be handy so we can access it everywhere in the code base...

On my other game engine(just for fun) written in Java used interface System and then create GLFWSystem then add it to the list in SystemManager or something like that. That way we can customize what code will be initialized. in this example, glfw or glew(if somebody likes to use that).

**Comment by LovelySanta** [comment]
> > On the other had, depending on the distributions, we might want/not want to have GLFW used; where containing it inside the WindowsWindow (where we are actualy using it), could help to keep GLFW contained to where it is used in the code base...
> 
> On my other game engine(just for fun) written in Java used interface System and then create GLFWSystem then add it to the list in SystemManager or something like that. That way we can customize what code will be initialized. in this example, glfw or glew(if somebody likes to use that).

That is the path cherno will take as far as I know. Even go as far as conditional includes... This should be a co-op:

1. Core.h should decide what parts of the system will be used (defined with macros)
    - Conditionaly include required files, so unused files are not compiled
    - Determine what systems will be used
2. Systems class as runtime access
    - Init/Run/Shutdown routines
    - static members that characterize the system

**Comment by Puddlestomper** [comment]
We should make a task list for the 4 PRs that fix the known memory leaks. After they are merged this issue can probably be closed, unless anyone knows of any other leaks?

**Comment by LovelySanta** [comment]
I don't see how forgetting to call OnDetach on layers currently causes any leaks? (currently working on the task list)

**Comment by IshoAntar** [comment]
That's because if we don't call it, the ImGui layer's `ImGuiLayer.cpp` OnDetach won't get called (which frees the memory allocated by ImGui), hence, the memory is leaked.

**Comment by LovelySanta** [comment]
Yap, ImGui is indeed an issue, I'll add it to the list (I only looked at examplelayer)

**Comment by moskittle** [comment]
> I'm having the same problem!! Memory leaks just by moving the demo window or moving it outside of the application + it drops a lot of FPS & lags when moving the demo window as you can see.. 16 FPS; That's definitely a bug either in Hazel or ImGui docking branch. p.s I'm using the latest commit.
> ![image](https://user-images.githubusercontent.com/30192597/57565001-b8e80900-73b5-11e9-90c9-0d6b1c9df28b.png)

How did you render the CPU and GPU info?

**Comment by WhoseTheNerd** [comment]
> > I'm having the same problem!! Memory leaks just by moving the demo window or moving it outside of the application + it drops a lot of FPS & lags when moving the demo window as you can see.. 16 FPS; That's definitely a bug either in Hazel or ImGui docking branch. p.s I'm using the latest commit.
> > ![image](https://user-images.githubusercontent.com/30192597/57565001-b8e80900-73b5-11e9-90c9-0d6b1c9df28b.png)
> 
> How did you render the CPU and RAM info?

He is using MSI Burner and Riva statistics

**Comment by LovelySanta** [comment]
All found memory leaks are fixed. Can anyone re-check if they still happen? Maybe even analyse where they originate from?

**Comment by LovelySanta** [comment]
Closing this as it is running fine on the current base and all known issues are fixed. If we have any other leaks, we can open specific issues related to them instead of keeping an (old) thread open.

**Comment by csp256** [comment]
Funny timing, was about to comment that I left Hazel (dev branch) open over the weekend and found it sluggish when I came back. (just a few FPS, usually >>60) I have not yet diagnosed the problem, but worth keeping in mind.

**Comment by LovelySanta** [comment]
I don't think the dev branch has these fixes implemented to start with even?
