### ISSUE TITLE
TODO list before major work

### ISSUE THREAD

**Issue by TheCherno** [TheCherno/Hazel#561]
- [x] Add ApplicationSpecification with custom working directory (to fix Sandbox not working out of the box)
- [x] Textures in SpriteRendererComponent don't get serialized
- [x] Merge dev into master again (because of PRs)
- [x] Save feature (#516)
- [x] Better circle collider visualization (#517)
- [ ] Hazelnut scene titles (#528)
- [ ] Readme/logo stuff (#519 and #541)
- [ ] Fixed physics collider visualization offset (#555)
